language: android
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - cmake

android:
  components:
    - tools
    - platform-tools
    - ndk-bundle

before_install:
  - wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip
  - unzip android-ndk-r19-linux-x86_64.zip -d $HOME
  - export ANDROID_NDK=$HOME/android-ndk-r19
  - mkdir "$ANDROID_HOME/licenses" || true		
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"		
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"	

script:
    - bash build.sh
