language: cpp
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - cmake
      - build-essential

before_install:
  - wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip
  - unzip -qq android-ndk-r19-linux-x86_64.zip -d $HOME
  - export ANDROID_NDK=$HOME/android-ndk-r19
  - $ANDROID_NDK/ndk-build --version

script:
  - bash build.sh
