name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install packages
        run: |
          sudo apt-get -y install build-essential cmake
      - name: Install Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip -qq android-ndk-r23b-linux.zip -d $HOME
          export ANDROID_NDK=$HOME/android-ndk-r23b
          "$ANDROID_NDK/ndk-build --version"
      - name: Build
        run: |
          ./build.sh
      - name: Git Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*
