name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Android NDK Path
        run: |
          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
          "$ANDROID_NDK/ndk-build --version"
      - name: Build
        run: |
          ./build.sh
      - name: Git Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*
